const fs = require('fs');
const path = require('path');

const rostersDir = path.join(__dirname, '../src/data/rosters');
const indexFile = path.join(rostersDir, 'index.json');
const outputFile = path.join(__dirname, '../src/data/real_rosters_2025_26.js');

console.log('Reading index.json...');
const index = JSON.parse(fs.readFileSync(indexFile, 'utf8'));

let output = `// This file is generated by dev/build_rosters.js
// Do not edit this file directly.

(function() {
  if (typeof window === 'undefined' && typeof global !== 'undefined') {
    global.window = global.window || {};
  }
  window.REAL_ROSTERS = window.REAL_ROSTERS || {};

`;

for (const [teamName, fileName] of Object.entries(index)) {
  console.log(`Processing ${teamName}...`);
  const filePath = path.join(rostersDir, fileName);
  const data = fs.readFileSync(filePath, 'utf8');
  output += `  window.REAL_ROSTERS["${teamName}"] = ${data.trim()};\n\n`;
}

output += `})();\n`;

fs.writeFileSync(outputFile, output, 'utf8');
console.log('Successfully rebuilt src/data/real_rosters_2025_26.js');