// tools/trim_rosters.js
// Usage: node tools/trim_rosters.js
// This script loads data/real_rosters_2025_26.js in a sandboxed VM, then for each team
// trims the players array to 26 players. If a numeric `value` field is present it
// will keep the top 26 by value. If no numeric values exist for a team, it will
// truncate the array by removing players from the end (you can edit behaviour).

const fs = require('fs');
const vm = require('vm');
const path = require('path');

const rostersPath = path.join(__dirname, '..', 'data', 'real_rosters_2025_26.js');
if (!fs.existsSync(rostersPath)) {
  console.error('Could not find', rostersPath);
  process.exit(1);
}

const src = fs.readFileSync(rostersPath, 'utf8');
const sandbox = { window: {} };
try {
  vm.runInNewContext(src, sandbox, {timeout: 1000});
} catch (err) {
  console.error('Error executing roster file in sandbox:', err.message);
  process.exit(1);
}

const rosters = sandbox.window && sandbox.window.REAL_ROSTERS;
if (!rosters) {
  console.error('No window.REAL_ROSTERS found in file. Aborting.');
  process.exit(1);
}

let changed = false;
for (const teamName of Object.keys(rosters)) {
  const players = rosters[teamName];
  if (!Array.isArray(players)) continue;
  if (players.length <= 26) continue;

  // Check for numeric value fields
  const hasNumericValue = players.some(p => typeof p.value === 'number');

  if (hasNumericValue) {
    // Keep top 26 by numeric value
    players.sort((a,b) => (b.value || 0) - (a.value || 0));
    rosters[teamName] = players.slice(0, 26);
    console.log(`Trimmed ${teamName}: kept top 26 by numeric value (was ${players.length})`);
  } else {
    // Try to parse a human-readable value string (like "40,00 M €") in p.value if it's a string
    const parsed = players.map(p => {
      const copy = Object.assign({}, p);
      if (typeof copy.value === 'string') {
        // Convert formats like "40,00 M €" or "600 mil €" to numeric millions
        const s = copy.value.replace(/\s/g, '').replace(/\./g, '').replace(/\€/g, '');
        // Handle formats with M (millions) or mil (thousands)
        const mMatch = s.match(/([\d,]+)M/i);
        const milMatch = s.match(/([\d,]+)mil/i);
        if (mMatch) {
          const num = parseFloat(mMatch[1].replace(',', '.'));
          copy._parsedValue = isNaN(num) ? null : num; // millions
        } else if (milMatch) {
          const num = parseFloat(milMatch[1].replace(',', '.'));
          copy._parsedValue = isNaN(num) ? null : num/1000; // convert thousands to millions
        } else {
          // fallback: try to extract plain number
          const numMatch = s.match(/([\d,]+)/);
          if (numMatch) {
            const num = parseFloat(numMatch[1].replace(',', '.'));
            // heuristic: if >100 assume it's thousands -> millions
            copy._parsedValue = num > 100 ? num/1000 : num;
          } else copy._parsedValue = null;
        }
      }
      return copy;
    });

    const anyParsed = parsed.some(p => typeof p._parsedValue === 'number');
    if (anyParsed) {
      // sort by parsed value desc
      players.sort((a,b) => ((b._parsedValue||0) - (a._parsedValue||0)));
      rosters[teamName] = players.slice(0,26);
      console.log(`Trimmed ${teamName}: parsed string values and kept top 26 (was ${players.length})`);
    } else {
      // No value info available: fallback to trimming last entries
      rosters[teamName] = players.slice(0,26);
      console.log(`Trimmed ${teamName}: no value info found, truncated to 26 (was ${players.length})`);
    }
  }
  changed = true;
}

if (!changed) {
  console.log('No teams required trimming.');
  process.exit(0);
}

// Serialize rosters back to file format
function serialize(R) {
  const lines = [];
  lines.push('// real_rosters_2025_26.js (generated by tools/trim_rosters.js)');
  lines.push('// Each team: window.REAL_ROSTERS["Team"] = [ {name, position, value?}, ... ];');
  lines.push('');
  lines.push('window.REAL_ROSTERS = window.REAL_ROSTERS || {};');
  lines.push('');
  for (const team of Object.keys(R)) {
    lines.push(`window.REAL_ROSTERS['${team.replace(/'/g, "\\'")}'] = [`);
    for (const p of R[team]) {
      const obj = { name: p.name, position: p.position };
      if (typeof p.value === 'number') obj.value = p.value;
      else if (typeof p._parsedValue === 'number') obj.value = p._parsedValue;
      lines.push('  ' + JSON.stringify(obj) + ',');
    }
    lines.push('];');
    lines.push('');
  }
  return lines.join('\n');
}

const out = serialize(rosters);
fs.writeFileSync(rostersPath, out, 'utf8');
console.log('Wrote trimmed rosters back to', rostersPath);
